### PR TITLE
include minutes from last meeting

### PR DESCRIPTION
**Pull request by ha0ye**

### CODE REVIEW

**Comment by ha0ye** [comment]
Deploy preview for *uf-carpentries* ready!

Built with commit 67b727c0418c392ed06cff12c812a6bdb32f544a

https://deploy-preview-39--uf-carpentries.netlify.com

**Comment by josephaandreoli** [comment]
I approve

**Comment by gaurav** [comment]
Thanks, @josephaandreoli and @ha0ye! The minutes are now up at https://www.uf-carpentries.org/minutes/board-2019-04-30/. In the future, we plan to update the minutes on the website before approval by the board.

**Comment by ha0ye** [comment]
Netlify is now doing deploy previews for PRs (they show up as comments under my name). There’s still a bit of navigating from the preview to get to the minutes though.

**Comment by gaurav** [comment]
True! Unfortunately, the page header appears to be using absolute URLs, so it's particularly hard to navigate to the board minutes from there. It also sounded like the board would prefer an e-mail that just says "minutes are up at [url], please check them and see if you approve" rather than having to deal with pull requests.

**Comment by ha0ye** [comment]
Yah, it seems less than ideal.

**Pull request merged**
