### PR TITLE
Added description of REC program

### PR DESCRIPTION
**Pull request by picardis**

### CODE REVIEW

**Comment by ha0ye** [comment]
Deploy preview for *uf-carpentries* ready!

Built with commit 3c1b2300f80fe01c4b6d671fe3c836b36235922f

https://deploy-preview-49--uf-carpentries.netlify.com

**Comment by ha0ye** [comment]
Looks great! Thanks @picardis for writing this up and getting this program going!

**Comment by picardis** [comment]
Should this be under https://www.uf-carpentries.org/about/workshops?

**Comment by ha0ye** [comment]
> Should this be under https://www.uf-carpentries.org/about/workshops?

Hmm, I feel like it's important enough to warrant its own page. Linking to it in both https://www.uf-carpentries.org/about/workshops and https://www.uf-carpentries.org/about would be good.

**Pull request merged**
